name: Actualizador de Canales

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install cloudscraper

      - name: Ejecutar script
        run: python cazador.py

      - name: Subir cambios a GitHub
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add mexico.json
          git commit -m "Link de Distrito Comedia actualizado" || exit 0
          git push
