name: Actualizador de Canales

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Actualizado para mejor soporte de yt-dlp

      - name: Instalar librerías
        run: pip install cloudscraper yt-dlp

      - name: Ejecutar script
        run: python cazador.py

      - name: Subir cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Agregamos ambos archivos para que se guarden los cambios de México y USA
          git add mexico.json usa.json
          git commit -m "Actualización automática: ZAZ y Animal Planet" || exit 0
          git push origin main
